apiVersion: v1
kind: Secret
metadata:
  name: keycloak-secrets
type: Opaque
stringData:
  dbHost: ""
  dbPort: ""
  dbUser: ""
  dbPassword: ""
  dbDatabase: ""
  host: ""
  adminUser: ""
  adminPassword: ""
